### ISSUE TITLE
Do we still need Dynamo leftovers in the installer package?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Installer#209]
#### Descriptions:
While working on other stuff, I have just noticed Dynamo leftovers in _Components_ and _Directories_ .wxs files. Do we still need them? If not, probs worth running a proper ctrl+f against the repo and cull em all 😉

**Comment by FraserGreenroyd** [comment]
Hi @pawelbaran thanks for asking - I've double checked what @albinber did and the left over references in `Components` and `Directories` are still needed at the moment.

Similar to the old assemblies folder (when we used to install BHoM to `%AppData%` rather than `%ProgramData%` as we do now), if someone is upgrading BHoM to the latest version, we want to clean up any outdated stuff, but we have to tell the installer about them in the first place.

If someone is upgrading from a version of BHoM with Dynamo (anything pre-7.0), but we did not include the references we have, the pre-existing installation files would remain (leading to issues with mismatched DLL versions!), similar to if we did not tell the installer to remove the old `%AppData%` folder (for people upgrading from a very long time ago to now).

You can see the old `%AppData%` reference [here](https://github.com/BHoM/BHoM_Installer/blob/main/InstallerCore/Directories.wxs#L38) from L38 to L41, and then again in `Components` on [L75](https://github.com/BHoM/BHoM_Installer/blob/main/InstallerCore/Components.wxs#L75) where we tell the installer to remove the folder.

Thus, we do need to retain information within the installer about Dynamo for the purposes to tidying up after ourselves now that we don't support Dynamo installation (at least for the time being, that may change again in the future!).

We could rename it to `OldDynamo`, however, I felt that might cause more confusion because, unlike with the `%AppData%` change, we don't have a 'new' Dynamo installation process (whereas `%AppData%` is called `OldInstallFolder` because `%ProgramData%` became the new install folder). Hence I took the decision with @albinber to leave the reference names as they were for the time being.

Hope that makes sense - I'm going to close the issue as there isn't any action necessary on this from a development stand point, but please do reopen if you have any further queries 😄
